module.exports = [
    // Whites
    { names: ["white"], hex: "ffffff" },
    { names: ["snow"], hex: "fffafa" },
    { names: ["ghostwhite"], hex: "f8f8ff" },
    { names: ["mintcream"], hex: "f5fffa" },
    { names: ["ivory"], hex: "fffff0" },
    { names: ["azure"], hex: "f0ffff" },
    { names: ["floralwhite"], hex: "fffaf0" },
    { names: ["honeydew"], hex: "f0fff0" },
    { names: ["aliceblue"], hex: "f0f8ff" },
    { names: ["lavenderblush"], hex: "fff0f5" },
    { names: ["seashell"], hex: "fff5ee" },
    { names: ["whitesmoke"], hex: "f5f5f5" },
    { names: ["oldlace"], hex: "fdf5e6" },
    { names: ["linen"], hex: "faf0e6" },
    { names: ["mistyrose"], hex: "ffe4e1" },
    { names: ["beige"], hex: "f5f5dc" },
    { names: ["antiquewhite"], hex: "faebd7" },
    // Grays and Blacks
    { names: ["black"], hex: "000000" },
    { names: ["darkslategray", "darkslategrey"], hex: "2f4f4f" },
    { names: ["dimgray", "dimgrey"], hex: "696969" },
    { names: ["slategray", "slategrey"], hex: "708090" },
    { names: ["gray", "grey"], hex: "808080" },
    { names: ["lightslategray", "lightslategrey"], hex: "778899" },
    { names: ["darkgray", "darkgrey"], hex: "a9a9a9" },
    { names: ["silver"], hex: "c0c0c0" },
    { names: ["lightgray", "lightgrey"], hex: "d3d3d3" },
    { names: ["gainsboro"], hex: "dcdcdc" },
    // Reds
    { names: ["darkred"], hex: "8b0000" },
    { names: ["red"], hex: "ff0000" },
    { names: ["firebrick"], hex: "b22222" },
    { names: ["crimson"], hex: "dc143c" },
    { names: ["indianred"], hex: "cd5c5c" },
    { names: ["lightcoral"], hex: "f08080" },
    { names: ["salmon"], hex: "fa8072" },
    { names: ["darksalmon"], hex: "e9967a" },
    { names: ["lightsalmon"], hex: "ffa07a" },
    // Oranges
    { names: ["orangered"], hex: "ff4500" },
    { names: ["tomato"], hex: "ff6347" },
    { names: ["darkorange"], hex: "ff8c00" },
    { names: ["coral"], hex: "ff7f50" },
    { names: ["orange"], hex: "ffa500" },
    // Yellow
    { names: ["darkkhaki"], hex: "bdb76b" },
    { names: ["gold"], hex: "ffd700" },
    { names: ["khaki"], hex: "f0e68c" },
    { names: ["peachpuff"], hex: "ffdab9" },
    { names: ["yellow"], hex: "ffff00" },
    { names: ["palegoldenrod"], hex: "eee8aa" },
    { names: ["moccasin"], hex: "ffe4b5" },
    { names: ["papayawhip"], hex: "ffefd5" },
    { names: ["lightgoldenrodyellow"], hex: "fafad2" },
    { names: ["lemonchiffon"], hex: "fffacd" },
    { names: ["lemonyellow"], hex: "ffffe0" },
    // Greens
    { names: ["darkgreen"], hex: "006400" },
    { names: ["green"], hex: "008000" },
    { names: ["darkolivegreen"], hex: "556b2f" },
    { names: ["forestgreen"], hex: "228b22" },
    { names: ["seagreen"], hex: "2e8b57" },
    { names: ["olive"], hex: "808000" },
    { names: ["olivedrab"], hex: "3cb371" },
    { names: ["limegreen"], hex: "32cd32" },
    { names: ["lime"], hex: "00ff00" },
    { names: ["springgreen"], hex: "00ff7f" },
    { names: ["mediumspringgreen"], hex: "00fa9a" },
    { names: ["darkseagreen"], hex: "8fbc8f" },
    { names: ["mediumaquamarine"], hex: "66cdaa" },
    { names: ["yellowgreen"], hex: "9acd32" },
    { names: ["lawngreen"], hex: "7cfc00" },
    { names: ["chartreuse"], hex: "7fff00" },
    { names: ["lightgreen"], hex: "90ee90" },
    { names: ["greenyellow"], hex: "adff2f" },
    { names: ["palegreen"], hex: "98fb98" },
    // Cyans
    { names: ["teal"], hex: "008080" },
    { names: ["darkcyan"], hex: "008b8b" },
    { names: ["lightseagreen"], hex: "20b2aa" },
    { names: ["cadetblue"], hex: "5f9ea0" },
    { names: ["darkturquoise"], hex: "00ced1" },
    { names: ["mediumturquoise"], hex: "48d1cc" },
    { names: ["turquoise"], hex: "40e0d0" },
    { names: ["aqua", "cyan"], hex: "00ffff" },
    { names: ["aquamarine"], hex: "7fffd4" },
    { names: ["paleturquoise"], hex: "afeeee" },
    { names: ["lightcyan"], hex: "e0ffff" },
    // Blues
    { names: ["navy", "navyblue"], hex: "000080" },
    { names: ["darkblue"], hex: "00008b" },
    { names: ["mediumblue"], hex: "0000cd" },
    { names: ["blue"], hex: "0000ff" },
    { names: ["midnightblue"], hex: "191970" },
    { names: ["royalblue"], hex: "4169e1" },
    { names: ["steelblue"], hex: "4682b4" },
    { names: ["dodgerblue"], hex: "1e90ff" },
    { names: ["deepskyblue"], hex: "00bfff" },
    { names: ["cornflowerblue"], hex: "6495ed" },
    { names: ["skyblue"], hex: "87ceeb" },
    { names: ["lightskyblue"], hex: "87cefa" },
    { names: ["lightsteelblue"], hex: "b0c4de" },
    { names: ["lightblue"], hex: "add8e6" },
    { names: ["powderblue"], hex: "b0e0e6" },
    // Purples and Pinks
    { names: ["indigo"], hex: "4b0082" },
    { names: ["purple"], hex: "800080" },
    { names: ["darkmagenta"], hex: "8b008b" },
    { names: ["darkviolet"], hex: "9400d3" },
    { names: ["darkslateblue"], hex: "483d8b" },
    { names: ["blueviolet"], hex: "8a2be2" },
    { names: ["darkorchid"], hex: "9932cc" },
    { names: ["magenta"], hex: "ff00ff" },
    { names: ["slateblue"], hex: "6a5acd" },
    { names: ["mediumslateblue"], hex: "7b68ee" },
    { names: ["mediumorchid"], hex: "ba55d3" },
    { names: ["mediumpurple"], hex: "9370db" },
    { names: ["orchid"], hex: "da70d6" },
    { names: ["violet"], hex: "ee82ee" },
    { names: ["plum"], hex: "dda0dd" },
    { names: ["thistle"], hex: "d8bfd8" },
    { names: ["lavender"], hex: "e6e6fa" },
    // Browns
    { names: ["maroon"], hex: "800000" },
    { names: ["brown"], hex: "a52a2a" },
    { names: ["saddlebrown"], hex: "8b4513" },
    { names: ["sienna"], hex: "a0522d" },
    { names: ["chocolate"], hex: "d2691e" },
    { names: ["darkgoldenrod"], hex: "b8860b" },
    { names: ["peru"], hex: "cd853f" },
    { names: ["rosybrown"], hex: "bc8f8f" },
    { names: ["goldenrod"], hex: "daa520" },
    { names: ["sandybrown"], hex: "f4a460" },
    { names: ["tan"], hex: "d2b48c" },
    { names: ["burlywood"], hex: "deb887" },
    { names: ["wheat"], hex: "f5deb3" },
    { names: ["navajowhite"], hex: "ffdead" },
    { names: ["bisque"], hex: "ffe4c4" },
    { names: ["blanchedalmond"], hex: "ffebcd" },
    { names: ["cornsilk"], hex: "fff8dc" },
    // Custom
    { names: ["trigamblue", "trigonometryblue"], hex: "3f48cc" },
    { names: ["colonorange", "betterorange", "bestorange"], hex: "ff8000" },
    { names: ["obamiumbrown", "conbrown"], hex: "917570" },
    { names: ["poggersblue", "poggyblue", "pogblue", "noahblue"], hex: "4350ca" },
    { names: ["nitrolime", "gamergreen"], hex: "69ff61" },
    // Discord colors
    { names: ["discordblue", "discordblurple", "blurple"], hex: "5865f2" },
    { names: ["discordblueold", "olddiscordblue", "discordblueog", "discordblurpleold", "olddiscordblurple", "discordblurpleog", "blurpleold", "oldblurple", "blurpleog"], hex: "7389da" },
    { names: ["discordgreen"], hex: "57f287" },
    { names: ["discordyellow"], hex: "fee75c" },
    { names: ["discordfuchsia", "discordmagenta"], hex: "eb459e" },
    { names: ["discordred"], hex: "ed4245" },
    { names: ["discordblack"], hex: "23272a" },
    { names: ["discordgray", "discordgrey"], hex: "36393f" },
    { names: ["discorddarkgray", "discorddarkgrey"], hex: "2f3136" },
    { names: ["discordnitroboostingpink", "nitroboostingpink", "discordnitropink", "nitropink"], hex: "ff6bfa" },
    { names: ["discordonlinegreen", "onlinegreen"], hex: "3ba55c" },
    { names: ["discordidleyellow", "idleyellow"], hex: "faa61a" },
    { names: ["discordinvisiblegray", "discordinvisiblegrey", "invisiblegray", "invisiblegrey"], hex: "747f8d" },
];